### PR TITLE
Adapt to upstream changes

### PR DESCRIPTION
**Pull request by peterjc123**
NVCC is now a supported compiler.

### CODE REVIEW

**Comment by peterjc123** [comment]
Tested in https://github.com/pytorch/pytorch/pull/39635.

**Comment by ezyang** [comment]
Does this mean we don't need this fork anymore?

**Comment by peterjc123** [comment]
> Does this mean we don't need this fork anymore?

Nope, we still have HCC.

**Comment by mszhanyi** [comment]
@peterjc123 what does HCC stand for?

To fix https://github.com/pytorch/pytorch/issues/37928
I tried to make some changes on latest sccache and it works locally.

Shall I submit a PR to mozilla/sccache or pytorch/sccache?
cc @ezyang

**Comment by peterjc123** [comment]
@mszhanyi HCC = the compiler for HIP (just like CUDA, but for AMD), which isn't used for Windows. So if the official one works fine, you may just switch to use that instead for Windows.

**Pull request merged**
