### PR TITLE
Port the features to upstream/master

### PR DESCRIPTION
**Pull request by peterjc123**
Related issue: https://github.com/pytorch/pytorch/issues/24982

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
@soumith Could you please merge it?

**Comment by ezyang** [comment]
@peterjc123 you should have merge rights, go for it!

**Comment by peterjc123** [comment]
@ezyang No, actually I couldn't find the green button.
image

**Comment by soumith** [comment]
weird, i gave you write access. let me check

**Comment by soumith** [comment]
it was my bad. I gave you Triage access instead of Write.
But now fixed, you have Write access

**Pull request merged**
